// The Columbus AFB site profile (plan Step 2c, part B): the SOF's own data for KCBM. The parts every US base shares, and their sources, are in us-base.js.
// Weather standards: AFMAN 11-202V3 4.16 and 4.17.3 (part F, usaf-standards.js), NOAA MRMS radar and NASA GOES-East satellite (part C), no lightning picture, the WPC fronts, and (part E) FAA airspace, FAA NOTAMs (keyed) and aviationweather.gov SIGMETs, G-AIRMETs and PIREPs.
import { usBase, towns } from './us-base.js';
import { USAF_STANDARDS } from './usaf-standards.js';

export const KCBM = usBase({
  icao: 'KCBM',
  name: 'Columbus AFB',
  shortName: 'Columbus',
  // The usual alternates: a guess Dad said to use for now.
  usualAlternates: ['KGTR', 'KBHM'],
  alternatesSource: 'a guess (nearby fields with an ILS) that Dad said to use for now, 7 Oct 2026; Dad to confirm',
  // [id, name, lat, lon (GeoNames, for drawing only), built-up radius NM (estimate), tallest block ft (estimate)]
  towns: towns([
    ['columbus', 'Columbus', 33.4957, -88.4273, 2.2, 100],
    ['caledonia', 'Caledonia', 33.6829, -88.3245, 0.5, 30],
    ['west-point', 'West Point', 33.6076, -88.6503, 1.2, 40],
    ['aberdeen', 'Aberdeen', 33.8251, -88.5437, 1, 40],
    ['starkville', 'Starkville', 33.4505, -88.8196, 2, 100],
  ]),
  tourField: { icao: 'KGTR', label: 'Golden Triangle' },
  // 2.9° W: NOAA WMM2025 at the field for 8 Oct 2026 (-2.91°), to a tenth (us-base.js).
  magVarDeg: -2.9,
  // FAA open data airspace inside the base's 900 NM square (faa-airspace/, generated by tools/faa-airspace.mjs), loaded only when the 3D view opens here.
  loadAirspace: () => import('./faa-airspace/kcbm.js'),
  // The USAF bases' weather standards (part F; Dad, 8 Oct 2026).
  standards: USAF_STANDARDS,
});
