// The Laughlin AFB site profile (plan Step 2c, part B): the SOF's own data for KDLF. The parts every US base shares, and their sources, are in us-base.js.
// Weather standards: AFMAN 11-202V3 4.16 and 4.17.3 (part F, usaf-standards.js), NOAA MRMS radar and NASA GOES-East satellite (part C), no lightning picture, the WPC fronts, and (part E) FAA airspace, FAA NOTAMs (keyed) and aviationweather.gov SIGMETs, G-AIRMETs and PIREPs.
import { AIRSPACE_LOADERS } from '../../../airfields/airspace/areas.js';
import { usBase, towns } from './us-base.js';
import { USAF_STANDARDS } from './usaf-standards.js';

export const KDLF = usBase({
  icao: 'KDLF',
  name: 'Laughlin AFB',
  shortName: 'Laughlin',
  // The usual alternates: Dad's.
  usualAlternates: ['KDRT', 'KSAT', 'KSJT', 'KABI', 'KLRD'],
  alternatesSource: 'Dad, 7 Oct 2026 (SOF plan Step 2c)',
  // [id, name, lat, lon (GeoNames, for drawing only), built-up radius NM (estimate), tallest block ft (estimate)]
  towns: towns([
    ['del-rio', 'Del Rio', 29.3627, -100.8968, 2.5, 100],
    ['ciudad-acuna', 'Ciudad Acuña', 29.3232, -100.9522, 3, 80],
    ['brackettville', 'Brackettville', 29.3105, -100.4179, 0.6, 30],
    ['eagle-pass', 'Eagle Pass', 28.7091, -100.4995, 2.2, 80],
    ['uvalde', 'Uvalde', 29.2097, -99.7862, 1.6, 60],
  ]),
  tourField: { icao: 'KDRT', label: 'Del Rio' },
  // 4.7° E: NOAA WMM2025 at the field for 8 Oct 2026 (4.65°), to a tenth (us-base.js).
  magVarDeg: 4.7,
  // FAA open data airspace inside the base's 900 NM square (src/airfields/airspace/faa/, generated by tools/faa-airspace.mjs), loaded only when the 3D view opens here.
  loadAirspace: AIRSPACE_LOADERS.KDLF,
  // The FAA CIFP's instrument approaches to the base and its usual alternates (approaches/, generated by tools/cifp-approaches.mjs), loaded when needed.
  loadApproaches: () => import('./approaches/kdlf.js'),
  // The USAF bases' weather standards (part F; Dad, 8 Oct 2026).
  standards: USAF_STANDARDS,
});
