// The Vance AFB site profile (plan Step 2c, part B): the SOF's own data for KEND. The parts every US base shares, and their sources, are in us-base.js.
// No weather standards yet (Limits not set), NOAA MRMS radar and NASA GOES-East satellite (part C), no lightning picture, the WPC fronts, and (part E) FAA airspace, FAA NOTAMs (keyed) and aviationweather.gov SIGMETs, G-AIRMETs and PIREPs.
import { usBase, towns } from './us-base.js';

export const KEND = usBase({
  icao: 'KEND',
  name: 'Vance AFB',
  shortName: 'Vance',
  // The usual alternates: a guess Dad said to use for now.
  usualAlternates: ['KWDG', 'KOKC'],
  alternatesSource: 'a guess (nearby fields with an ILS) that Dad said to use for now, 7 Oct 2026; Dad to confirm',
  // [id, name, lat, lon (GeoNames, for drawing only), built-up radius NM (estimate), tallest block ft (estimate)]
  towns: towns([
    ['enid', 'Enid', 36.3956, -97.8784, 2.6, 150],
    ['waukomis', 'Waukomis', 36.2803, -97.8981, 0.5, 30],
    ['hennessey', 'Hennessey', 36.1092, -97.8987, 0.7, 30],
  ]),
  tourField: { icao: 'KWDG', label: 'Enid Woodring' },
  // 3.3° E: NOAA WMM2025 at the field for 8 Oct 2026 (3.26°), to a tenth (us-base.js).
  magVarDeg: 3.3,
  // FAA open data airspace inside the base's 900 NM square (faa-airspace/, generated by tools/faa-airspace.mjs), loaded only when the 3D view opens here.
  loadAirspace: () => import('./faa-airspace/kend.js'),
});
