// The NAS Corpus Christi site profile (plan Step 2c, part B): the SOF's own data for KNGP. The parts every US base shares, and their sources, are in us-base.js.
// No weather standards yet (Limits not set), NOAA MRMS radar and NASA GOES-East satellite (part C), no lightning picture, the WPC fronts, and (part E) FAA airspace, FAA NOTAMs (keyed) and aviationweather.gov SIGMETs, G-AIRMETs and PIREPs.
import { usBase, towns } from './us-base.js';

export const KNGP = usBase({
  icao: 'KNGP',
  name: 'NAS Corpus Christi',
  shortName: 'Corpus Christi',
  // The usual alternates: a guess Dad said to use for now.
  usualAlternates: ['KCRP', 'KNQI'],
  alternatesSource: 'a guess (nearby fields with an ILS) that Dad said to use for now, 7 Oct 2026; Dad to confirm',
  // [id, name, lat, lon (GeoNames, for drawing only), built-up radius NM (estimate), tallest block ft (estimate)]
  towns: towns([
    ['corpus-christi', 'Corpus Christi', 27.8006, -97.3964, 5, 300],
    ['portland', 'Portland', 27.8773, -97.3239, 1.5, 40],
    ['port-aransas', 'Port Aransas', 27.8339, -97.0611, 1, 50],
    ['robstown', 'Robstown', 27.7903, -97.6689, 1, 30],
    ['kingsville', 'Kingsville', 27.5159, -97.8561, 1.8, 60],
  ]),
  tourField: { icao: 'KCRP', label: 'Corpus Christi Intl' },
  // 2.8° E: NOAA WMM2025 at the field for 8 Oct 2026 (2.82°), to a tenth (us-base.js).
  magVarDeg: 2.8,
  // FAA open data airspace inside the base's 900 NM square (faa-airspace/, generated by tools/faa-airspace.mjs), loaded only when the 3D view opens here.
  loadAirspace: () => import('./faa-airspace/kngp.js'),
  // The FAA CIFP's instrument approaches to the base and its usual alternates (approaches/, generated by tools/cifp-approaches.mjs), loaded when needed.
  loadApproaches: () => import('./approaches/kngp.js'),
});
