// The San Angelo (Mathis Field) site profile (Dad, 8 Oct 2026: an eighth SOF location, after the 3D pan and area work): the SOF's own data for KSJT. The parts
// every US base shares, and their sources, are in us-base.js. Weather standards: Moose Jaw's (Dad, 8 Oct 2026: "KSJT uses moosejaw rules (its the
// detachment)"), by reference to the CYMJ profile, NOAA MRMS radar and NASA GOES-East satellite, no lightning
// picture, the WPC fronts, FAA airspace (KSJT is Class D, surface to 4,400 ft MSL, in the FAA data), FAA NOTAMs (keyed) and aviationweather.gov SIGMETs,
// G-AIRMETs and PIREPs.
import { usBase, towns } from './us-base.js';
import { CYMJ } from './cymj.js';

export const KSJT = usBase({
  icao: 'KSJT',
  name: 'San Angelo (Mathis Field)',
  shortName: 'San Angelo',
  // The usual alternates: Dad's.
  usualAlternates: ['KABI', 'KMAF', 'KDLF'],
  alternatesSource: 'Dad, 8 Oct 2026 (SOF plan Step 2c)',
  // [id, name, lat, lon (GeoNames, for drawing only), built-up radius NM (estimate), tallest block ft (estimate)]
  towns: towns([
    ['san-angelo', 'San Angelo', 31.4638, -100.437, 3.5, 180],
    ['grape-creek', 'Grape Creek', 31.5793, -100.5476, 0.6, 30],
    ['mertzon', 'Mertzon', 31.2618, -100.8173, 0.5, 30],
    ['robert-lee', 'Robert Lee', 31.8924, -100.4848, 0.5, 30],
    ['ballinger', 'Ballinger', 31.7382, -99.9473, 1, 50],
  ]),
  tourField: { icao: 'KABI', label: 'Abilene' },
  // 4.6° E: NOAA WMM2025 at the field for 8 Oct 2026 (4.58°), to a tenth (us-base.js).
  magVarDeg: 4.6,
  // FAA open data airspace inside the base's 900 NM square (faa-airspace/, generated by tools/faa-airspace.mjs), loaded only when the 3D view opens here.
  loadAirspace: () => import('./faa-airspace/ksjt.js'),
  // Moose Jaw's rules, by reference (one copy): San Angelo is the Moose Jaw detachment (Dad, 8 Oct 2026).
  standards: CYMJ.standards,
});
