// The Sheppard AFB site profile (plan Step 2c, part B): the SOF's own data for KSPS. The parts every US base shares, and their sources, are in us-base.js.
// Weather standards: AFMAN 11-202V3 4.16 and 4.17.3 (part F, usaf-standards.js), NOAA MRMS radar and NASA GOES-East satellite (part C), no lightning picture, the WPC fronts, and (part E) FAA airspace, FAA NOTAMs (keyed) and aviationweather.gov SIGMETs, G-AIRMETs and PIREPs.
import { AIRSPACE_LOADERS } from '../../../airfields/airspace/areas.js';
import { usBase, towns } from './us-base.js';
import { USAF_STANDARDS } from './usaf-standards.js';

export const KSPS = usBase({
  icao: 'KSPS',
  name: 'Sheppard AFB',
  shortName: 'Sheppard',
  // The usual alternates: a guess Dad said to use for now.
  usualAlternates: ['KLAW', 'KDFW'],
  alternatesSource: 'a guess (nearby fields with an ILS) that Dad said to use for now, 7 Oct 2026; Dad to confirm',
  // [id, name, lat, lon (GeoNames, for drawing only), built-up radius NM (estimate), tallest block ft (estimate)]
  towns: towns([
    ['wichita-falls', 'Wichita Falls', 33.9137, -98.4934, 3.5, 200],
    ['burkburnett', 'Burkburnett', 34.0979, -98.5706, 1.2, 40],
    ['iowa-park', 'Iowa Park', 33.9515, -98.6687, 1, 30],
    ['electra', 'Electra', 34.0293, -98.919, 0.8, 30],
    ['lawton', 'Lawton', 34.6087, -98.3903, 3, 150],
  ]),
  tourField: { icao: 'KLAW', label: 'Lawton' },
  // 3.6° E: NOAA WMM2025 at the field for 8 Oct 2026 (3.55°), to a tenth (us-base.js).
  magVarDeg: 3.6,
  // FAA open data airspace inside the base's 900 NM square (src/airfields/airspace/faa/, generated by tools/faa-airspace.mjs), loaded only when the 3D view opens here.
  loadAirspace: AIRSPACE_LOADERS.KSPS,
  // The FAA CIFP's instrument approaches to the base and its usual alternates (approaches/, generated by tools/cifp-approaches.mjs), loaded when needed.
  loadApproaches: () => import('./approaches/ksps.js'),
  // The USAF bases' weather standards (part F; Dad, 8 Oct 2026).
  standards: USAF_STANDARDS,
});
