// KNGP's airspace for the SOF's 3D view: GENERATED by tools/faa-airspace.mjs (do not edit by hand; run it again each 56-day cycle).
// From the FAA's open aeronautical data (AIS ArcGIS feature services, public domain), inside the base's 450 NM square; the shape is the one
// airspace-data.js describes. Outlines thinned to within 0.1 NM and rounded to 4 decimals; for a picture, not for navigation.
// Cross-check against AP/1A / AP/1B (pages to be added).

/** The dataset(s) and their FAA edit dates, for the profile's note. */
export const SOURCE = "FAA open aeronautical data: not generated yet (run tools/faa-airspace.mjs)";

export const AIRSPACE = Object.freeze([
]);
